alias fabric='cd /Users/nizanifrach/git-repo/fabric && workon fab-env'
alias ha='cd /Users/nizanifrach/git-repo/helm-assembly'
alias k='kubectl'
alias kgp='kubectl get pods'
alias wkgp='watch kubectl get pods'
alias kdp='kubectl describe pod'
alias kgn='kubectl get namespaces'
alias flush='sudo killall -HUP mDNSResponder'
alias hu='helm upgrade --install --namespace $ENV $ENV charts/bizzabo --values=charts/bizzabo/values.yaml'
